# Generated by Django 5.2.6 on 2026-01-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('writername', models.CharField(max_length=100)),
            ],
        ),
    ]
