# Generated by Django 5.2.6 on 2026-01-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_report_unique_together_and_more'),
        ('posts', '0015_kitab'),
    ]

    operations = [
    ]
