# Generated by Django 5.2.6 on 2026-01-31 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_merge_20260131_1434'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('inappropriate', 'Uyğun deyil'), ('spam', 'Spam'), ('hate_speech', 'Nifrət nitqi'), ('violence', 'Şiddet'), ('copyright', 'Müəllif hüquqları'), ('other', 'Digər')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('post', 'user')},
        ),
    ]
